import React, { useEffect, useState } from 'react';
import {
  AbsoluteFill, continueRender, delayRender,
  staticFile, useCurrentFrame, useVideoConfig, spring
} from 'remotion';
import { THEME } from '../theme';

// ─── Types ─────────────────────────────────────────────────────────────────────

interface WordTiming {
  word: string;
  start: number;   // seconds
  end: number;     // seconds
}

interface CaptionsProps {
  // Path to the .words.json file generated by prepare_reel.py
  // Falls back gracefully if file not found
  wordTimingsFile: string;
}

// ─── Component ─────────────────────────────────────────────────────────────────

export const Captions: React.FC<CaptionsProps> = ({ wordTimingsFile }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const [handle] = useState(() => delayRender('Loading word timings'));
  const [wordTimings, setWordTimings] = useState<WordTiming[]>([]);
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    fetch(staticFile(wordTimingsFile))
      .then(res => {
        if (!res.ok) throw new Error(`${res.status}`);
        return res.json();
      })
      .then((data: WordTiming[]) => {
        setWordTimings(data);
        setLoaded(true);
        continueRender(handle);
      })
      .catch(() => {
        // File missing or malformed — fail silently, no captions shown
        setLoaded(true);
        continueRender(handle);
      });
  }, [wordTimingsFile, handle]);

  if (!loaded || wordTimings.length === 0) return null;

  const currentTime = frame / fps;

  // Find which words are in the current "caption window"
  // Show a rolling window of words around the currently spoken word
  const WINDOW_WORDS = 5; // how many words visible at once

  const activeIndex = wordTimings.findIndex(
    w => currentTime >= w.start && currentTime < w.end
  );

  // If between words (tiny gaps) — keep last spoken word active
  const effectiveIndex = activeIndex === -1
    ? wordTimings.filter(w => currentTime >= w.start).length - 1
    : activeIndex;

  if (effectiveIndex < 0) return null;

  // Rolling window: show WINDOW_WORDS centered around effectiveIndex
  const windowStart = Math.max(0, effectiveIndex - Math.floor(WINDOW_WORDS / 2));
  const windowEnd = Math.min(wordTimings.length, windowStart + WINDOW_WORDS);
  const windowWords = wordTimings.slice(windowStart, windowEnd);

  return (
    <AbsoluteFill style={{
      justifyContent: 'flex-end',
      alignItems: 'center',
      paddingBottom: 420,
      pointerEvents: 'none',
      zIndex: 200,
    }}>
      <div style={{
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        gap: '10px 14px',
        backgroundColor: 'rgba(8, 8, 14, 0.88)',
        padding: '22px 40px',
        borderRadius: 22,
        border: `1px solid ${THEME.border}`,
        boxShadow: `0 12px 48px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.04)`,
        maxWidth: '86%',
        backdropFilter: 'blur(8px)',
      }}>
        {windowWords.map((wordTiming, wi) => {
          const globalIndex = windowStart + wi;
          const isActive = globalIndex === effectiveIndex;
          const isPast = globalIndex < effectiveIndex;

          // Progress through the active word (0→1 over its duration)
          const wordProgress = isActive
            ? Math.max(0, Math.min(1,
                (currentTime - wordTiming.start) / Math.max(0.05, wordTiming.end - wordTiming.start)
              ))
            : 0;

          return (
            <span
              key={`${globalIndex}-${wordTiming.word}`}
              style={{
                fontFamily: THEME.fontSans,
                fontSize: 44,
                fontWeight: 800,
                textTransform: 'uppercase',
                letterSpacing: '0.02em',
                display: 'inline-block',
                // Active word: bright purple with glow + slight scale up
                // Past words: white (already said)
                // Future words: dim
                color: isActive
                  ? THEME.purple
                  : isPast
                  ? THEME.textPrimary
                  : 'rgba(255,255,255,0.25)',
                textShadow: isActive
                  ? `0 0 20px ${THEME.purple}99, 0 0 40px ${THEME.purple}44`
                  : 'none',
                transform: isActive ? `scale(1.12)` : 'scale(1)',
                transition: 'color 0.08s ease, transform 0.08s ease',
                // Underline progress on active word — fills left to right as word is spoken
                position: 'relative',
              }}
            >
              {wordTiming.word}
              {/* Word progress underline */}
              {isActive && (
                <span style={{
                  position: 'absolute',
                  bottom: -4,
                  left: 0,
                  height: 3,
                  width: `${wordProgress * 100}%`,
                  background: `linear-gradient(90deg, ${THEME.purple}, ${THEME.teal})`,
                  borderRadius: 2,
                  transition: 'width 0.05s linear',
                }} />
              )}
            </span>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};